/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.*;

import javax.swing.JOptionPane;

import Obj.Locacoes;
import Obj.Veiculo;
import modeloDao.DAO_LOCACAO;
import java.sql.*;
/**
 *
 * @author drika
 */
public class FormCarro extends javax.swing.JFrame {
 DAO_LOCACAO dl = new DAO_LOCACAO();
	Veiculo v = new Veiculo();
	Locacoes l = new Locacoes();
    /**
     * Creates new form FormClient
     */
    public FormCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlPesquisarModelo = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jtfPesquisarModelo = new javax.swing.JTextField();
        jtfPlaca = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jlLocacaoVeiculos = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jlDataInicial = new javax.swing.JLabel();
        jlDataTerminal = new javax.swing.JLabel();
        jlFuncionario = new javax.swing.JLabel();
        jtfFuncionario = new javax.swing.JTextField();
        jtfDataInicial = new javax.swing.JTextField();
        jtfDataTerminal = new javax.swing.JTextField();
        jbPesquisarLocacao = new javax.swing.JButton();
        jlInforme = new javax.swing.JLabel();
        jbCadastrarLocacao = new javax.swing.JButton();
        jtfInfoCpfCliente = new javax.swing.JTextField();
        jbListar = new javax.swing.JButton();
        jbcTipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jlPesquisarModelo.setText("Modelo");

        jlCpf.setText("CPF/CNPJ");

        jbAlterar.setBackground(new java.awt.Color(0, 153, 153));
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbNovo.setBackground(new java.awt.Color(0, 255, 102));
        jbNovo.setText("Novo");

        jbFechar.setForeground(new java.awt.Color(255, 51, 51));
        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jlLocacaoVeiculos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlLocacaoVeiculos.setText("Locação de veículos");

        jlPlaca.setText("Placa do veículo");

        jlDataInicial.setText("Data inicial");

        jlDataTerminal.setText("Data Terminal");

        jlFuncionario.setText("Funcionário");

        jtfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFuncionarioActionPerformed(evt);
            }
        });

        jbPesquisarLocacao.setText("Pesquisar locação");
        jbPesquisarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarLocacaoActionPerformed(evt);
            }
        });

        jlInforme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlInforme.setText("Informe o CPF do cliente ");

        jbCadastrarLocacao.setText("Cadastrar locação");
        jbCadastrarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarLocacaoActionPerformed(evt);
            }
        });

        jtfInfoCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInfoCpfClienteActionPerformed(evt);
            }
        });

        jbListar.setText("Listar veículos disponíveis");
        jbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarActionPerformed(evt);
            }
        });

        jbcTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carro", "Moto", " " }));

        jLabel1.setText("Selecione o tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbListar)
                                .addGap(18, 18, 18)
                                .addComponent(jlInforme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfInfoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbAlterar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbNovo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbFechar))
                                .addComponent(jbPesquisarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLocacaoVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlPesquisarModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jbcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCpf)
                                    .addComponent(jlDataInicial))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfCpf)
                                    .addComponent(jtfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlPlaca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfPlaca))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlDataTerminal)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfDataTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jlFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbCadastrarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf)
                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPlaca)
                            .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDataInicial)
                            .addComponent(jlDataTerminal)
                            .addComponent(jtfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDataTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlPesquisarModelo)
                                .addComponent(jtfPesquisarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlFuncionario)
                                .addComponent(jtfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jbCadastrarLocacao))
                    .addComponent(jlLocacaoVeiculos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfInfoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlInforme)
                    .addComponent(jbListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNovo)
                        .addComponent(jbFechar))
                    .addComponent(jbAlterar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg3.png"))); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24512345.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(806, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
           l.setCPF(jtfCpf.getText());
	   l.setData_incio(jtfDataInicial.getText());
           l.setData_fim(jtfDataTerminal.getText());
           l.setPlaca(jtfPlaca.getText());
           l.setFuncionario(jtfFuncionario.getText());
           l.setModelo(jtfPesquisarModelo.getText());
           l.setTipo((String) jbcTipo.getSelectedItem());
        
           dl.altera(l);
           
            jtfCpf.setText("");
            jtfDataInicial.setText("");
	    jtfDataTerminal.setText("");
            jtfPlaca.setText("");
            jtfFuncionario.setText("");
            jtfPesquisarModelo.setText("");
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFuncionarioActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbCadastrarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarLocacaoActionPerformed
        // TODO add your handling code here:
        
           l.setCPF(jtfCpf.getText());
	   l.setData_incio(jtfDataInicial.getText());
           l.setData_fim(jtfDataTerminal.getText());
           l.setPlaca(jtfPlaca.getText());
           l.setFuncionario(jtfFuncionario.getText());
           l.setModelo(jtfPesquisarModelo.getText());
           l.setTipo((String) jbcTipo.getSelectedItem());
           

	    jtfCpf.setText("");
            jtfDataInicial.setText("");
	    jtfDataTerminal.setText("");
            jtfPlaca.setText("");
            jtfFuncionario.setText("");
            jtfPesquisarModelo.setText("");
            
	    		
	    dl.Aluga(l);
    }//GEN-LAST:event_jbCadastrarLocacaoActionPerformed

    private void jbPesquisarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarLocacaoActionPerformed
        l = dl.busca(jtfInfoCpfCliente.getText());
        
        jtfCpf.setText(l.getCPF());
        jtfDataInicial.setText(l.getData_incio());
	jtfDataTerminal.setText(l.getData_fim());
        jtfPlaca.setText(l.getPlaca());
        jtfFuncionario.setText(l.getFuncionario());
        jtfPesquisarModelo.setText(l.getCPF());
        
        
        
    }//GEN-LAST:event_jbPesquisarLocacaoActionPerformed

    private void jtfInfoCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInfoCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInfoCpfClienteActionPerformed

    private void jbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarActionPerformed
        // TODO add your handling code here:
        List<Veiculo> Veiculo = new ArrayList<Veiculo>();
        
		
		Veiculo = dl.lista();
		
		
		String str = "";
		for(int i = 0; i < Veiculo.size(); i++){
                     
                    str+="Tipo :" + Veiculo.get(i).getTipo()+ "\n";
                    str+="Marca:" + Veiculo.get(i).getMarca()+ "\n";
                    str+="Modelo :" + Veiculo.get(i).getModelo()+ "\n";
                    str+="Placa :" + Veiculo.get(i).getPlaca()+ "\n";
                    str+="Cor :" + Veiculo.get(i).getCor()+ "\n";
                     str+="Ano :" + Veiculo.get(i).getAno()+ "\n";
                    str+="Valor diaria :" + Veiculo.get(i).getValor_diaria()+ "\n";
                    str+="Status :" + Veiculo.get(i).getStatus()+ "\n ----------\n";
                    }
                JOptionPane.showMessageDialog(null,str);
        
    }//GEN-LAST:event_jbListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCadastrarLocacao;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbListar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisarLocacao;
    private javax.swing.JComboBox jbcTipo;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlDataInicial;
    private javax.swing.JLabel jlDataTerminal;
    private javax.swing.JLabel jlFuncionario;
    private javax.swing.JLabel jlInforme;
    private javax.swing.JLabel jlLocacaoVeiculos;
    private javax.swing.JLabel jlPesquisarModelo;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JTextField jtfDataInicial;
    private javax.swing.JTextField jtfDataTerminal;
    private javax.swing.JTextField jtfFuncionario;
    private javax.swing.JTextField jtfInfoCpfCliente;
    private javax.swing.JTextField jtfPesquisarModelo;
    private javax.swing.JTextField jtfPlaca;
    // End of variables declaration//GEN-END:variables
}
