/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import modeloDao.DAO_CLIENTE;
import Obj.Cliente;
import Obj.Pessoa;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author drika
 */
public class FormClient extends javax.swing.JFrame {
    
    DAO_CLIENTE dc = new DAO_CLIENTE();
	Cliente c = new Cliente();
	Pessoa p = new Pessoa();

    /**
     * Creates new form FormClient
     */
    public FormClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlPesquisarCliente = new javax.swing.JLabel();
        jlCadastarCliente = new javax.swing.JLabel();
        jlCadastrarSexo = new javax.swing.JLabel();
        jlCadastrarEndereco = new javax.swing.JLabel();
        jlCadastrarCpf = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlAreaCadastro = new javax.swing.JLabel();
        jtfCadastrarCliente = new javax.swing.JTextField();
        jcbSexo = new javax.swing.JComboBox<String>();
        jtfCadastrarEndereco = new javax.swing.JTextField();
        jtfPesquisarCpf = new javax.swing.JTextField();
        jtfCadastrarCpf = new javax.swing.JTextField();
        jlCadastrarIdade = new javax.swing.JLabel();
        jtfCadastrarIdade = new javax.swing.JTextField();
        jbConsultarCliente = new javax.swing.JButton();
        jlCadastrarCelular = new javax.swing.JLabel();
        jtfCadastrarCelular = new javax.swing.JTextField();
        jbCadastrarCliente = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jlCliente = new javax.swing.JLabel();
        jbAlterarCliente = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        icone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        jlPesquisarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPesquisarCliente.setText("Pesquisar Clientes");

        jlCadastarCliente.setText("Nome");

        jlCadastrarSexo.setText("Sexo");

        jlCadastrarEndereco.setText("Endereco");

        jlCadastrarCpf.setText("CPF/CNPJ");

        jlCpf.setText("CPF/CNPJ");

        jlAreaCadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlAreaCadastro.setText("Cadastar Clientes");

        jtfCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCadastrarClienteActionPerformed(evt);
            }
        });

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));

        jtfCadastrarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCadastrarEnderecoActionPerformed(evt);
            }
        });

        jlCadastrarIdade.setText("Idade");

        jtfCadastrarIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCadastrarIdadeActionPerformed(evt);
            }
        });

        jbConsultarCliente.setText("Consultar");
        jbConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarClienteActionPerformed(evt);
            }
        });

        jlCadastrarCelular.setText("Celular");

        jbCadastrarCliente.setText("Cadastrar");
        jbCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarClienteActionPerformed(evt);
            }
        });

        jbApagar.setText("Apagar");
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jlCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCliente.setText("Area do cliente");

        jbAlterarCliente.setText("Alterar");
        jbAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAreaCadastro)
                .addGap(282, 282, 282))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultarCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlPesquisarCliente)
                        .addGap(278, 278, 278))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCadastarCliente)
                                    .addComponent(jlCadastrarSexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jlCadastrarIdade))
                                    .addComponent(jtfCadastrarCliente)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfCadastrarIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCadastrarEndereco)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jtfCadastrarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCadastrarCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCadastrarCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlCadastrarCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCadastrarCelular)))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCadastrarCliente)
                        .addGap(4, 4, 4)
                        .addComponent(jbAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbApagar)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesquisarCliente)
                    .addComponent(jlCliente))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCpf)
                            .addComponent(jtfPesquisarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbConsultarCliente))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCadastarCliente)
                            .addComponent(jtfCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCadastrarCpf)
                            .addComponent(jtfCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jlAreaCadastro)))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCadastrarSexo)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCadastrarIdade)
                    .addComponent(jtfCadastrarIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCadastrarCelular)
                    .addComponent(jtfCadastrarCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCadastrarEndereco)
                    .addComponent(jtfCadastrarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarCliente)
                    .addComponent(jbApagar)
                    .addComponent(jbAlterarCliente))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg3.png"))); // NOI18N

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/212445.png"))); // NOI18N
        icone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(icone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(806, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jtfCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCadastrarClienteActionPerformed
        // TODO add your handling code here:	
    }//GEN-LAST:event_jtfCadastrarClienteActionPerformed
//
    private void jtfCadastrarIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCadastrarIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCadastrarIdadeActionPerformed
// Botao Cadastrar Cliente
    private void jbCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarClienteActionPerformed
        // TODO add your handling code here:
           c.setNome(jtfCadastrarCliente.getText());
	   c.setEndereco(jtfCadastrarEndereco.getText());
	   c.setTelefone(jtfCadastrarCelular.getText());
           c.setIdade(jtfCadastrarIdade.getText());
           c.setCPF(jtfCadastrarCpf.getText());
           c.setSexo((String) jcbSexo.getSelectedItem());

	    jtfCadastrarCliente.setText("");
	    jtfCadastrarEndereco.setText("");
            jtfCadastrarCpf.setText("");
	    jtfCadastrarCelular.setText("");
            jtfCadastrarIdade.setText("");
            
	    		
	    dc.inserePessoa(c);
            
            
    }//GEN-LAST:event_jbCadastrarClienteActionPerformed

    private void iconeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconeActionPerformed
// Botao Fechar
    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
       // this.dispose();
        dc.apaga(jtfCadastrarCliente.getText());

			jtfCadastrarCliente.setText("");
			jtfCadastrarEndereco.setText("");
			jtfCadastrarCelular.setText("");
                        jtfCadastrarIdade.setText("");
			jtfCadastrarCpf.setText("");
		
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jtfCadastrarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCadastrarEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCadastrarEnderecoActionPerformed

    private void jbConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarClienteActionPerformed
        // TODO add your handling code here:
        c = dc.busca(jtfPesquisarCpf.getText());
			jtfCadastrarCliente.setText(c.getNome());
			jtfCadastrarEndereco.setText(c.getEndereco());
                        jtfCadastrarIdade.setText(c.getIdade());
                        jtfCadastrarCpf.setText(c.getCPF());
			jtfCadastrarCelular.setText(c.getTelefone());
                        
    }//GEN-LAST:event_jbConsultarClienteActionPerformed

    private void jbAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarClienteActionPerformed
        // TODO add your handling code here:
        c.setNome(jtfCadastrarCliente.getText());
	c.setEndereco(jtfCadastrarEndereco.getText());
	c.setIdade(jtfCadastrarIdade.getText());
        c.setCPF(jtfCadastrarCpf.getText());
        c.setSexo((String) jcbSexo.getSelectedItem());
        c.setTelefone(jtfCadastrarCelular.getText());
                       
        
           dc.altera(c);
			jtfCadastrarCliente.setText("");
			jtfCadastrarEndereco.setText("");
			jtfCadastrarCelular.setText("");
                        jtfCadastrarIdade.setText("");
			jtfCadastrarCpf.setText("");
              
			
			
			
    }//GEN-LAST:event_jbAlterarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton icone;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAlterarCliente;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCadastrarCliente;
    private javax.swing.JButton jbConsultarCliente;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jlAreaCadastro;
    private javax.swing.JLabel jlCadastarCliente;
    private javax.swing.JLabel jlCadastrarCelular;
    private javax.swing.JLabel jlCadastrarCpf;
    private javax.swing.JLabel jlCadastrarEndereco;
    private javax.swing.JLabel jlCadastrarIdade;
    private javax.swing.JLabel jlCadastrarSexo;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlPesquisarCliente;
    private javax.swing.JTextField jtfCadastrarCelular;
    private javax.swing.JTextField jtfCadastrarCliente;
    private javax.swing.JTextField jtfCadastrarCpf;
    private javax.swing.JTextField jtfCadastrarEndereco;
    private javax.swing.JTextField jtfCadastrarIdade;
    private javax.swing.JTextField jtfPesquisarCpf;
    // End of variables declaration//GEN-END:variables
}
