/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connect.ConectaBD;

/**
 *
 * @author drika
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConectaBD conecta = new ConectaBD();
    
    public TelaPrincipal() {
        initComponents();
      //  conecta.solicitaConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAreaCarro1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonAreaCarro = new javax.swing.JButton();
        jButtonAreaFuncionario = new javax.swing.JButton();
        jButtonAreaCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/74472.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 90, 50, 65);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9155c4307d5d5ec451ac5f4a54b0d181_1.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 260, 50, 50);

        jButtonAreaCarro1.setText("Acessar");
        jButtonAreaCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaCarro1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAreaCarro1);
        jButtonAreaCarro1.setBounds(380, 340, 77, 25);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Menu Veículo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 310, 148, 22);

        jButton1.setText("Acessar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 340, 79, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Menu Motos");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 310, 100, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24512345.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 90, 50, 66);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/212445.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 90, 50, 65);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Área do funcionário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 154, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Área do cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 160, 117, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Locação de veículo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 160, 148, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconemoto_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 260, 60, 60);

        jButtonAreaCarro.setText("Acessar");
        jButtonAreaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaCarroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAreaCarro);
        jButtonAreaCarro.setBounds(490, 190, 77, 25);

        jButtonAreaFuncionario.setText("Acessar");
        jButtonAreaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAreaFuncionario);
        jButtonAreaFuncionario.setBounds(40, 190, 77, 25);

        jButtonAreaCliente.setText("Acessar");
        jButtonAreaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAreaCliente);
        jButtonAreaCliente.setBounds(270, 190, 77, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Escolha qual área deseja acessar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 30, 256, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-grey.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 630, 480);

        setSize(new java.awt.Dimension(636, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Botoes iniciais
    
    // Botao Caroo
    private void jButtonAreaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaCarroActionPerformed
        FormCarro carro = new FormCarro();
        carro.setVisible(true);
        carro.setTitle("Area de Locação");
        carro.setResizable(false);
    }//GEN-LAST:event_jButtonAreaCarroActionPerformed
//Botao Funcionario
    private void jButtonAreaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaFuncionarioActionPerformed
        FormFuncionario funcionario = new FormFuncionario();
        funcionario.setVisible(true);
        funcionario.setTitle("Area do Funcionário");
        funcionario.setResizable(false);
    }//GEN-LAST:event_jButtonAreaFuncionarioActionPerformed

//Botao Area Cliente
    
    private void jButtonAreaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaClienteActionPerformed
        FormClient client = new FormClient();
        client.setVisible(true);
        client.setTitle("Area do Cliente");
        client.setResizable(false);

    }//GEN-LAST:event_jButtonAreaClienteActionPerformed

    private void jButtonAreaCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaCarro1ActionPerformed
        FormCarroCadastro carro = new FormCarroCadastro();
        carro.setVisible(true);
        carro.setTitle("Gerenciar carros");
        carro.setResizable(false);
    }//GEN-LAST:event_jButtonAreaCarro1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormMotoCadastro moto = new FormMotoCadastro();
        moto.setVisible(true);
        moto.setTitle("Gereciar Motos");
        moto.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAreaCarro;
    private javax.swing.JButton jButtonAreaCarro1;
    private javax.swing.JButton jButtonAreaCliente;
    private javax.swing.JButton jButtonAreaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
